
# https://docs.github.com/ja/actions/reference/workflows-and-actions/workflow-syntax
# GMT - 9_hour

name: newer

on:
  schedule:
    - cron: "0 0-9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate atom
        id: gen_atom
        run: |
          python ./python/tver/tver_get_newer.py

          # atom_file="${steps.gen_atom.outputs.atom_file}"

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f "./feed/tver/*.atom"
          git diff --cached --quiet || git commit -m "Update atom feed"
          git push
